name: deploy to lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: .NET Lambda build and deploy
      run: |
        dotnet tool install -g Amazon.Lambda.Tools
        cd src 
        dotnet lambda deploy-function --region