name: deploy to lambda

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: .NET Lambda build and deploy
      run: |
        dotnet tool install --global Amazon.Lambda.Tools --version 5.1.1
        export AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        cd src 
        dotnet lambda deploy-function